[package]
name = "risc-v"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-methods = { path = "methods" }
warp = "0.3"
tokio = { version = "1", features = ["full"] }
risc0-zkvm = "1.2.3"
hex-literal = "0.4.1"
serde = "1.0.217"
bincode = "1.3.3"
hex = "0.4.3"
